version: '3.1'
services:
  database:
    image: cassandra:3
    ports:
      - "9042:9042"
  kong:
    image: kong:latest
    environment:
      - "KONG_DATABASE=cassandra"
      - "KONG_CASSANDRA_CONTACT_POINTS=database"
      - "KONG_PG_HOST=database"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"